In [1]:
import sys

print(sys.executable)

D:\Projects\nyc311-heat-report\.venv\Scripts\python.exe

In [2]:
import pandas as pd

In [3]:
import requests

In [4]:
API_URL = "https://data.cityofnewyork.us/resource/erm2-nwe9.json"

params = {
    "$limit": 5
}

response = requests.get(API_URL, params=params)

print(response.status_code)

200

In [5]:
records = response.json()

print(len(records))

5

In [7]:
records[0]

{'unique_key': '69704572',
 'created_date': '2026-07-14T02:04:29.000',
 'agency': 'NYPD',
 'agency_name': 'New York City Police Department',
 'complaint_type': 'Noise - Commercial',
 'descriptor': 'Loud Music/Party',
 'location_type': 'Club/Bar/Restaurant',
 'incident_zip': '10457',
 'incident_address': '2241 WASHINGTON AVENUE',
 'street_name': 'WASHINGTON AVENUE',
 'cross_street_1': 'EAST 182 STREET',
 'cross_street_2': 'EAST 183 STREET',
 'intersection_street_1': 'EAST 182 STREET',
 'intersection_street_2': 'EAST 183 STREET',
 'address_type': 'ADDRESS',
 'city': 'BRONX',
 'landmark': 'WASHINGTON AVENUE',
 'status': 'In Progress',
 'community_board': '06 BRONX',
 'council_district': '15',
 'police_precinct': 'Precinct 48',
 'bbl': '2030380038',
 'borough': 'BRONX',
 'x_coordinate_state_plane': '1013601',
 'y_coordinate_state_plane': '250569',
 'open_data_channel_type': 'PHONE',
 'park_facility_name': 'Unspecified',
 'park_borough': 'BRONX',
 'latitude': '40.85438013820117',
 'longitude': '-73.8939013093197',
 'location': {'type': 'Point',
  'coordinates': [-73.89390130932, 40.854380138201]},
 ':@computed_region_f5dn_yrer': '35',
 ':@computed_region_yeji_bk3q': '5',
 ':@computed_region_sbqj_enih': '31',
 ':@computed_region_92fq_4b7q': '22'}

In [8]:
records[1]

{'unique_key': '69700295',
 'created_date': '2026-07-14T02:03:55.000',
 'agency': 'TLC',
 'agency_name': 'Taxi and Limousine Commission',
 'complaint_type': 'For Hire Vehicle Report',
 'descriptor': 'Driver Report - Non Passenger',
 'descriptor_2': 'Unsafe Driving',
 'location_type': 'Street',
 'incident_zip': '11208',
 'incident_address': '51 FORBELL STREET',
 'street_name': 'FORBELL STREET',
 'cross_street_1': '95 AVENUE',
 'cross_street_2': 'MC KINLEY AVENUE',
 'intersection_street_1': '95 AVENUE',
 'intersection_street_2': 'MC KINLEY AVENUE',
 'address_type': 'ADDRESS',
 'city': 'BROOKLYN',
 'landmark': 'FORBELL STREET',
 'status': 'In Progress',
 'community_board': '05 BROOKLYN',
 'council_district': '37',
 'police_precinct': 'Precinct 75',
 'bbl': '3041790018',
 'borough': 'BROOKLYN',
 'x_coordinate_state_plane': '1021711',
 'y_coordinate_state_plane': '187754',
 'open_data_channel_type': 'ONLINE',
 'park_facility_name': 'Unspecified',
 'park_borough': 'BROOKLYN',
 'taxi_pick_up_location': '51 FORBELL STREET, BROOKLYN, NY, 11208',
 'latitude': '40.68193885478958',
 'longitude': '-73.86493523841233',
 'location': {'type': 'Point',
  'coordinates': [-73.864935238412, 40.68193885479]},
 ':@computed_region_f5dn_yrer': '45',
 ':@computed_region_yeji_bk3q': '2',
 ':@computed_region_sbqj_enih': '47',
 ':@computed_region_92fq_4b7q': '37'}

In [9]:
# field names and dates fovorable format. some extra columns and metadata not needed.

In [10]:
df=pd.DataFrame(records)
df.columns.tolist()

['unique_key',
 'created_date',
 'agency',
 'agency_name',
 'complaint_type',
 'descriptor',
 'location_type',
 'incident_zip',
 'incident_address',
 'street_name',
 'cross_street_1',
 'cross_street_2',
 'intersection_street_1',
 'intersection_street_2',
 'address_type',
 'city',
 'landmark',
 'status',
 'community_board',
 'council_district',
 'police_precinct',
 'bbl',
 'borough',
 'x_coordinate_state_plane',
 'y_coordinate_state_plane',
 'open_data_channel_type',
 'park_facility_name',
 'park_borough',
 'latitude',
 'longitude',
 'location',
 ':@computed_region_f5dn_yrer',
 ':@computed_region_yeji_bk3q',
 ':@computed_region_sbqj_enih',
 ':@computed_region_92fq_4b7q',
 'descriptor_2',
 'taxi_pick_up_location']

In [11]:
df.columns

Index(['unique_key', 'created_date', 'agency', 'agency_name', 'complaint_type',
       'descriptor', 'location_type', 'incident_zip', 'incident_address',
       'street_name', 'cross_street_1', 'cross_street_2',
       'intersection_street_1', 'intersection_street_2', 'address_type',
       'city', 'landmark', 'status', 'community_board', 'council_district',
       'police_precinct', 'bbl', 'borough', 'x_coordinate_state_plane',
       'y_coordinate_state_plane', 'open_data_channel_type',
       'park_facility_name', 'park_borough', 'latitude', 'longitude',
       'location', ':@computed_region_f5dn_yrer',
       ':@computed_region_yeji_bk3q', ':@computed_region_sbqj_enih',
       ':@computed_region_92fq_4b7q', 'descriptor_2', 'taxi_pick_up_location'],
      dtype='str')

In [20]:


df2 = pd.read_csv(
    "data/raw/311_Service_Requests_from_2020_to_Present_20260325.csv",
    
)

df2.columns

C:\Users\Home\AppData\Local\Temp\ipykernel_14840\774556770.py:1: DtypeWarning: Columns (0: Incident Zip) have mixed types. Specify dtype option on import or set low_memory=False.
  df2 = pd.read_csv(

Index(['Unique Key', 'Created Date', 'Closed Date', 'Agency', 'Agency Name',
       'Problem (formerly Complaint Type)',
       'Problem Detail (formerly Descriptor)', 'Additional Details',
       'Location Type', 'Incident Zip', 'Status', 'Resolution Description',
       'Resolution Action Updated Date', 'City', 'Borough', 'Location'],
      dtype='str')

In [18]:
df2["Problem (formerly Complaint Type)"].value_counts()

Problem (formerly Complaint Type)
Noise - Residential                        394
Noise - Street/Sidewalk                    157
Noise - Commercial                         104
Illegal Parking                             85
Noise - Vehicle                             35
                                          ...
Animal-Abuse                                 1
Unsanitary Condition                         1
Commercial Disposal Complaint                1
Consumer Complaint                           1
Special Projects Inspection Team (SPIT)      1
Name: count, Length: 62, dtype: int64

In [23]:
df2["Problem (formerly Complaint Type)"].value_counts()["Heat/Hot Water"]

np.int64(1210)

In [26]:
# ==========================================
# Configuration
# ==========================================

In [27]:
API_URL = "https://data.cityofnewyork.us/resource/erm2-nwe9.json"

AGENCY = "HPD"

COMPLAINT_TYPE = "HEAT/HOT WATER"

In [28]:
# ==========================================
# Selected Columns
# ==========================================

In [29]:
selected_columns = [
    "unique_key",
    "created_date",
    "closed_date",
    "agency",
    "agency_name",
    "complaint_type",
    "descriptor",
    "descriptor_2",
    "location_type",
    "incident_zip",
    "incident_address",
    "street_name",
    "status",
    "due_date",
    "resolution_description",
    "resolution_action_updated_date",
    "borough",
    "community_board",
    "council_district",
    "bbl",
    "open_data_channel_type",
    "latitude",
    "longitude"
]
# Fields required for operational reporting, geographic analysis,
# complaint tracking, and Power BI dashboards.

# Filtered HPD Heat/Hot Water API Pull

In [30]:
selected_columns_string = ",".join(selected_columns)

params = {
    "$select": selected_columns_string,
    "$where": (
        f"agency = '{AGENCY}' "
        f"AND complaint_type = '{COMPLAINT_TYPE}'"
    ),
    "$order": "created_date DESC",
    "$limit": 5
}

response = requests.get(
    API_URL,
    params=params,
    timeout=30
)

response.raise_for_status()

records = response.json()

print("HTTP status:", response.status_code)
print("Rows returned:", len(records))
print("Request URL:")
print(response.url)

HTTP status: 200
Rows returned: 5
Request URL:
https://data.cityofnewyork.us/resource/erm2-nwe9.json?%24select=unique_key%2Ccreated_date%2Cclosed_date%2Cagency%2Cagency_name%2Ccomplaint_type%2Cdescriptor%2Cdescriptor_2%2Clocation_type%2Cincident_zip%2Cincident_address%2Cstreet_name%2Cstatus%2Cdue_date%2Cresolution_description%2Cresolution_action_updated_date%2Cborough%2Ccommunity_board%2Ccouncil_district%2Cbbl%2Copen_data_channel_type%2Clatitude%2Clongitude&%24where=agency+%3D+%27HPD%27+AND+complaint_type+%3D+%27HEAT%2FHOT+WATER%27&%24order=created_date+DESC&%24limit=5

In [31]:
records[0]

{'unique_key': '69699857',
 'created_date': '2026-07-13T23:43:26.000',
 'agency': 'HPD',
 'agency_name': 'Department of Housing Preservation and Development',
 'complaint_type': 'HEAT/HOT WATER',
 'descriptor': 'APARTMENT ONLY',
 'descriptor_2': 'HEAT ON IN SUMMER',
 'location_type': 'RESIDENTIAL BUILDING',
 'incident_zip': '10044',
 'incident_address': '516 MAIN STREET',
 'street_name': 'MAIN STREET',
 'status': 'Open',
 'resolution_description': 'The following complaint conditions are still open. HPD has already attempted to notify the property owner that the condition exists; the tenant should provide access for the owner to make the repair.  HPD may attempt to contact the tenant by phone to verify the correction of the condition or an HPD Inspector may attempt to conduct an inspection.',
 'resolution_action_updated_date': '2026-07-13T00:00:00.000',
 'borough': 'MANHATTAN',
 'community_board': '08 MANHATTAN',
 'council_district': '05',
 'bbl': '1013730030',
 'open_data_channel_type': 'PHONE',
 'latitude': '40.761023667231655',
 'longitude': '-73.95067267917607'}

In [32]:
heat_df = pd.DataFrame(records)

print("Shape:", heat_df.shape)
display(heat_df)

Shape: (5, 21)

,unique_key,created_date,agency,agency_name,complaint_type,descriptor,descriptor_2,location_type,incident_zip,incident_address,...,status,resolution_description,resolution_action_updated_date,borough,community_board,council_district,bbl,open_data_channel_type,latitude,longitude
0,69699857,2026-07-13T23:43:26.000,HPD,Department of Housing Preservation and Develop...,HEAT/HOT WATER,APARTMENT ONLY,HEAT ON IN SUMMER,RESIDENTIAL BUILDING,10044,516 MAIN STREET,...,Open,The following complaint conditions are still o...,2026-07-13T00:00:00.000,MANHATTAN,08 MANHATTAN,05,1013730030,PHONE,40.761023667231655,-73.95067267917607
1,69699710,2026-07-13T23:24:18.000,HPD,Department of Housing Preservation and Develop...,HEAT/HOT WATER,ENTIRE BUILDING,NO HOT WATER,RESIDENTIAL BUILDING,10468,2607 JEROME AVENUE,...,Open,This complaint is a duplicate of a building-wi...,2026-07-13T00:00:00.000,BRONX,07 BRONX,14,2032020055,ONLINE,40.86606572942326,-73.89850683939007
2,69710190,2026-07-13T23:09:13.000,HPD,Department of Housing Preservation and Develop...,HEAT/HOT WATER,ENTIRE BUILDING,NO HOT WATER,RESIDENTIAL BUILDING,10031,516 WEST 134 STREET,...,Open,The following complaint conditions are still o...,2026-07-13T00:00:00.000,MANHATTAN,09 MANHATTAN,07,1019870046,ONLINE,40.8188154188477,-73.95413073413812
3,69704144,2026-07-13T22:56:49.000,HPD,Department of Housing Preservation and Develop...,HEAT/HOT WATER,ENTIRE BUILDING,NO HOT WATER,RESIDENTIAL BUILDING,10468,2607 JEROME AVENUE,...,Open,This complaint is a duplicate of a building-wi...,2026-07-13T00:00:00.000,BRONX,07 BRONX,14,2032020055,ONLINE,40.86606572942326,-73.89850683939007
4,69705608,2026-07-13T22:32:46.000,HPD,Department of Housing Preservation and Develop...,HEAT/HOT WATER,APARTMENT ONLY,NO HOT WATER,RESIDENTIAL BUILDING,10033,562 WEST 175 STREET,...,Open,This complaint is a duplicate of a building-wi...,2026-07-13T00:00:00.000,MANHATTAN,12 MANHATTAN,10,1021310013,ONLINE,40.84506255240346,-73.93571937530402

In [33]:
print("Agencies:")
display(heat_df["agency"].value_counts(dropna=False))

print("Complaint types:")
display(heat_df["complaint_type"].value_counts(dropna=False))

Agencies:

agency
HPD    5
Name: count, dtype: int64

Complaint types:

complaint_type
HEAT/HOT WATER    5
Name: count, dtype: int64

In [34]:
print("Requested columns:", len(selected_columns))
print("Returned columns:", len(heat_df.columns))

missing_from_response = [
    column
    for column in selected_columns
    if column not in heat_df.columns
]

print("Fields absent from this five-row response:")
print(missing_from_response)

Requested columns: 23
Returned columns: 21
Fields absent from this five-row response:
['closed_date', 'due_date']

In [35]:
heat_df = heat_df.reindex(columns=selected_columns)

display(heat_df)

,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,descriptor_2,location_type,incident_zip,...,due_date,resolution_description,resolution_action_updated_date,borough,community_board,council_district,bbl,open_data_channel_type,latitude,longitude
0,69699857,2026-07-13T23:43:26.000,NaN,HPD,Department of Housing Preservation and Develop...,HEAT/HOT WATER,APARTMENT ONLY,HEAT ON IN SUMMER,RESIDENTIAL BUILDING,10044,...,NaN,The following complaint conditions are still o...,2026-07-13T00:00:00.000,MANHATTAN,08 MANHATTAN,05,1013730030,PHONE,40.761023667231655,-73.95067267917607
1,69699710,2026-07-13T23:24:18.000,NaN,HPD,Department of Housing Preservation and Develop...,HEAT/HOT WATER,ENTIRE BUILDING,NO HOT WATER,RESIDENTIAL BUILDING,10468,...,NaN,This complaint is a duplicate of a building-wi...,2026-07-13T00:00:00.000,BRONX,07 BRONX,14,2032020055,ONLINE,40.86606572942326,-73.89850683939007
2,69710190,2026-07-13T23:09:13.000,NaN,HPD,Department of Housing Preservation and Develop...,HEAT/HOT WATER,ENTIRE BUILDING,NO HOT WATER,RESIDENTIAL BUILDING,10031,...,NaN,The following complaint conditions are still o...,2026-07-13T00:00:00.000,MANHATTAN,09 MANHATTAN,07,1019870046,ONLINE,40.8188154188477,-73.95413073413812
3,69704144,2026-07-13T22:56:49.000,NaN,HPD,Department of Housing Preservation and Develop...,HEAT/HOT WATER,ENTIRE BUILDING,NO HOT WATER,RESIDENTIAL BUILDING,10468,...,NaN,This complaint is a duplicate of a building-wi...,2026-07-13T00:00:00.000,BRONX,07 BRONX,14,2032020055,ONLINE,40.86606572942326,-73.89850683939007
4,69705608,2026-07-13T22:32:46.000,NaN,HPD,Department of Housing Preservation and Develop...,HEAT/HOT WATER,APARTMENT ONLY,NO HOT WATER,RESIDENTIAL BUILDING,10033,...,NaN,This complaint is a duplicate of a building-wi...,2026-07-13T00:00:00.000,MANHATTAN,12 MANHATTAN,10,1021310013,ONLINE,40.84506255240346,-73.93571937530402

In [36]:
print("Shape:", heat_df.shape)

Shape: (5, 23)

In [37]:
assert response.status_code == 200
assert len(records) == 5
assert heat_df["agency"].dropna().eq("HPD").all()
assert heat_df["complaint_type"].dropna().eq("HEAT/HOT WATER").all()
assert heat_df["unique_key"].notna().all()

print("Filtered API validation passed.")

Filtered API validation passed.

D:\Projects\nyc311-heat-report