In [26]:
import sys

print(sys.executable)

D:\Projects\nyc311-heat-report\.venv\Scripts\python.exe

In [27]:
import pandas as pd

In [28]:
import requests

In [29]:
API_URL = "https://data.cityofnewyork.us/resource/erm2-nwe9.json"

params = {
    "$limit": 5
}

response = requests.get(API_URL, params=params)

print(response.status_code)

200

In [30]:
records = response.json()

print(len(records))

5

In [31]:
records[0]

{'unique_key': '69713633',
 'created_date': '2026-07-15T02:37:54.000',
 'agency': 'DOT',
 'agency_name': 'Department of Transportation',
 'complaint_type': 'Street Condition',
 'descriptor': 'Pothole',
 'incident_zip': '11420',
 'incident_address': '135 PLACE',
 'street_name': '135 PLACE',
 'cross_street_1': 'ALWICK ROAD',
 'cross_street_2': 'ROCKAWAY BOULEVARD',
 'address_type': 'BLOCKFACE',
 'city': 'QUEENS',
 'facility_type': 'N/A',
 'status': 'Open',
 'resolution_description': 'The Department of Transportation referred this complaint to the appropriate Maintenance Unit for repair.',
 'resolution_action_updated_date': '2026-07-15T02:37:54.000',
 'community_board': '10 QUEENS',
 'police_precinct': 'Precinct 106',
 'borough': 'QUEENS',
 'open_data_channel_type': 'UNKNOWN',
 'park_facility_name': 'Unspecified',
 'park_borough': 'QUEENS'}

In [32]:
records[1]

{'unique_key': '69718450',
 'created_date': '2026-07-15T02:37:04.000',
 'agency': 'DOT',
 'agency_name': 'Department of Transportation',
 'complaint_type': 'Street Condition',
 'descriptor': 'Pothole',
 'incident_zip': '11434',
 'incident_address': '157 STREET',
 'street_name': '157 STREET',
 'cross_street_1': '145 AVENUE',
 'cross_street_2': 'ROCKAWAY BOULEVARD',
 'address_type': 'BLOCKFACE',
 'city': 'QUEENS',
 'facility_type': 'N/A',
 'status': 'Open',
 'resolution_description': 'The Department of Transportation referred this complaint to the appropriate Maintenance Unit for repair.',
 'resolution_action_updated_date': '2026-07-15T02:37:04.000',
 'community_board': '13 QUEENS',
 'police_precinct': 'Unspecified',
 'borough': 'QUEENS',
 'open_data_channel_type': 'UNKNOWN',
 'park_facility_name': 'Unspecified',
 'park_borough': 'QUEENS'}

In [22]:
# field names and dates fovorable format. some extra columns and metadata not needed.

In [33]:
df=pd.DataFrame(records)
df.columns.tolist()

['unique_key',
 'created_date',
 'agency',
 'agency_name',
 'complaint_type',
 'descriptor',
 'incident_zip',
 'incident_address',
 'street_name',
 'cross_street_1',
 'cross_street_2',
 'address_type',
 'city',
 'facility_type',
 'status',
 'resolution_description',
 'resolution_action_updated_date',
 'community_board',
 'police_precinct',
 'borough',
 'open_data_channel_type',
 'park_facility_name',
 'park_borough']

In [34]:
df.columns

Index(['unique_key', 'created_date', 'agency', 'agency_name', 'complaint_type',
       'descriptor', 'incident_zip', 'incident_address', 'street_name',
       'cross_street_1', 'cross_street_2', 'address_type', 'city',
       'facility_type', 'status', 'resolution_description',
       'resolution_action_updated_date', 'community_board', 'police_precinct',
       'borough', 'open_data_channel_type', 'park_facility_name',
       'park_borough'],
      dtype='str')

In [ ]:


#df2 = pd.read_csv(
    "data/raw/311_Service_Requests_from_2020_to_Present_20260325.csv",
    
)

#df2.columns

In [ ]:
#df2["Problem (formerly Complaint Type)"].value_counts()

In [ ]:
#df2["Problem (formerly Complaint Type)"].value_counts()["Heat/Hot Water"]

In [ ]:
# ==========================================
# Configuration
# ==========================================

In [35]:
API_URL = "https://data.cityofnewyork.us/resource/erm2-nwe9.json"

AGENCY = "HPD"

COMPLAINT_TYPE = "HEAT/HOT WATER"

In [36]:
# ==========================================
# Selected Columns
# ==========================================

In [37]:
selected_columns = [
    "unique_key",
    "created_date",
    "closed_date",
    "agency",
    "agency_name",
    "complaint_type",
    "descriptor",
    "descriptor_2",
    "location_type",
    "incident_zip",
    "incident_address",
    "street_name",
    "status",
    "due_date",
    "resolution_description",
    "resolution_action_updated_date",
    "borough",
    "community_board",
    "council_district",
    "bbl",
    "open_data_channel_type",
    "latitude",
    "longitude"
]
# Fields required for operational reporting, geographic analysis,
# complaint tracking, and Power BI dashboards.

# Filtered HPD Heat/Hot Water API Pull

In [38]:
selected_columns_string = ",".join(selected_columns)

params = {
    "$select": selected_columns_string,
    "$where": (
        f"agency = '{AGENCY}' "
        f"AND complaint_type = '{COMPLAINT_TYPE}'"
    ),
    "$order": "created_date DESC",
    "$limit": 5
}

response = requests.get(
    API_URL,
    params=params,
    timeout=30
)

response.raise_for_status()

records = response.json()

print("HTTP status:", response.status_code)
print("Rows returned:", len(records))
print("Request URL:")
print(response.url)

HTTP status: 200
Rows returned: 5
Request URL:
https://data.cityofnewyork.us/resource/erm2-nwe9.json?%24select=unique_key%2Ccreated_date%2Cclosed_date%2Cagency%2Cagency_name%2Ccomplaint_type%2Cdescriptor%2Cdescriptor_2%2Clocation_type%2Cincident_zip%2Cincident_address%2Cstreet_name%2Cstatus%2Cdue_date%2Cresolution_description%2Cresolution_action_updated_date%2Cborough%2Ccommunity_board%2Ccouncil_district%2Cbbl%2Copen_data_channel_type%2Clatitude%2Clongitude&%24where=agency+%3D+%27HPD%27+AND+complaint_type+%3D+%27HEAT%2FHOT+WATER%27&%24order=created_date+DESC&%24limit=5

In [39]:
records[0]

{'unique_key': '69713457',
 'created_date': '2026-07-14T23:19:13.000',
 'agency': 'HPD',
 'agency_name': 'Department of Housing Preservation and Development',
 'complaint_type': 'HEAT/HOT WATER',
 'descriptor': 'ENTIRE BUILDING',
 'descriptor_2': 'NO HOT WATER',
 'location_type': 'RESIDENTIAL BUILDING',
 'incident_zip': '10025',
 'incident_address': '150 MANHATTAN AVENUE',
 'street_name': 'MANHATTAN AVENUE',
 'status': 'Open',
 'resolution_description': 'This complaint is a duplicate of a building-wide condition already reported by another tenant.  The original complaint is still open, and HPD may only need to confirm that the condition exists by inspecting one apartment.  If we cannot contact the tenant from the original complaint or get access to that apartment, HPD may attempt to contact the person who filed this complaint to verify the correction of the condition or may conduct an inspection of your unit. You can check HPDONLINE to see if a',
 'resolution_action_updated_date': '2026-07-14T00:00:00.000',
 'borough': 'MANHATTAN',
 'community_board': '07 MANHATTAN',
 'council_district': '07',
 'bbl': '1018420047',
 'open_data_channel_type': 'PHONE',
 'latitude': '40.79917399047754',
 'longitude': '-73.96108258488435'}

In [40]:
heat_df = pd.DataFrame(records)

print("Shape:", heat_df.shape)
display(heat_df)

Shape: (5, 21)

,unique_key,created_date,agency,agency_name,complaint_type,descriptor,descriptor_2,location_type,incident_zip,incident_address,...,status,resolution_description,resolution_action_updated_date,borough,community_board,council_district,bbl,open_data_channel_type,latitude,longitude
0,69713457,2026-07-14T23:19:13.000,HPD,Department of Housing Preservation and Develop...,HEAT/HOT WATER,ENTIRE BUILDING,NO HOT WATER,RESIDENTIAL BUILDING,10025,150 MANHATTAN AVENUE,...,Open,This complaint is a duplicate of a building-wi...,2026-07-14T00:00:00.000,MANHATTAN,07 MANHATTAN,07,1018420047,PHONE,40.79917399047754,-73.96108258488435
1,69711842,2026-07-14T22:51:30.000,HPD,Department of Housing Preservation and Develop...,HEAT/HOT WATER,ENTIRE BUILDING,NO HOT WATER,RESIDENTIAL BUILDING,11230,815 EAST 14 STREET,...,Open,This complaint is a duplicate of a building-wi...,2026-07-14T00:00:00.000,BROOKLYN,14 BROOKLYN,45,3066980001,ONLINE,40.629521027090476,-73.96314855928108
2,69715003,2026-07-14T22:39:26.000,HPD,Department of Housing Preservation and Develop...,HEAT/HOT WATER,ENTIRE BUILDING,NO HOT WATER,RESIDENTIAL BUILDING,11230,815 EAST 14 STREET,...,Open,The following complaint conditions are still o...,2026-07-14T00:00:00.000,BROOKLYN,14 BROOKLYN,45,3066980001,ONLINE,40.629521027090476,-73.96314855928108
3,69723138,2026-07-14T22:33:16.000,HPD,Department of Housing Preservation and Develop...,HEAT/HOT WATER,ENTIRE BUILDING,NO HOT WATER,RESIDENTIAL BUILDING,10021,1293 3 AVENUE,...,Open,The following complaint conditions are still o...,2026-07-14T00:00:00.000,MANHATTAN,08 MANHATTAN,05,1014290002,ONLINE,40.77124303640283,-73.95949953973174
4,69718280,2026-07-14T22:30:14.000,HPD,Department of Housing Preservation and Develop...,HEAT/HOT WATER,ENTIRE BUILDING,NO HOT WATER,RESIDENTIAL BUILDING,10003,223 2 AVENUE,...,Open,The following complaint conditions are still o...,2026-07-14T00:00:00.000,MANHATTAN,03 MANHATTAN,02,1004690030,ONLINE,40.732128314538684,-73.9851198208051

In [41]:
print("Agencies:")
display(heat_df["agency"].value_counts(dropna=False))

print("Complaint types:")
display(heat_df["complaint_type"].value_counts(dropna=False))

Agencies:

agency
HPD    5
Name: count, dtype: int64

Complaint types:

complaint_type
HEAT/HOT WATER    5
Name: count, dtype: int64

In [42]:
print("Requested columns:", len(selected_columns))
print("Returned columns:", len(heat_df.columns))

missing_from_response = [
    column
    for column in selected_columns
    if column not in heat_df.columns
]

print("Fields absent from this five-row response:")
print(missing_from_response)

Requested columns: 23
Returned columns: 21
Fields absent from this five-row response:
['closed_date', 'due_date']

In [43]:
heat_df = heat_df.reindex(columns=selected_columns)

display(heat_df)

,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,descriptor_2,location_type,incident_zip,...,due_date,resolution_description,resolution_action_updated_date,borough,community_board,council_district,bbl,open_data_channel_type,latitude,longitude
0,69713457,2026-07-14T23:19:13.000,NaN,HPD,Department of Housing Preservation and Develop...,HEAT/HOT WATER,ENTIRE BUILDING,NO HOT WATER,RESIDENTIAL BUILDING,10025,...,NaN,This complaint is a duplicate of a building-wi...,2026-07-14T00:00:00.000,MANHATTAN,07 MANHATTAN,07,1018420047,PHONE,40.79917399047754,-73.96108258488435
1,69711842,2026-07-14T22:51:30.000,NaN,HPD,Department of Housing Preservation and Develop...,HEAT/HOT WATER,ENTIRE BUILDING,NO HOT WATER,RESIDENTIAL BUILDING,11230,...,NaN,This complaint is a duplicate of a building-wi...,2026-07-14T00:00:00.000,BROOKLYN,14 BROOKLYN,45,3066980001,ONLINE,40.629521027090476,-73.96314855928108
2,69715003,2026-07-14T22:39:26.000,NaN,HPD,Department of Housing Preservation and Develop...,HEAT/HOT WATER,ENTIRE BUILDING,NO HOT WATER,RESIDENTIAL BUILDING,11230,...,NaN,The following complaint conditions are still o...,2026-07-14T00:00:00.000,BROOKLYN,14 BROOKLYN,45,3066980001,ONLINE,40.629521027090476,-73.96314855928108
3,69723138,2026-07-14T22:33:16.000,NaN,HPD,Department of Housing Preservation and Develop...,HEAT/HOT WATER,ENTIRE BUILDING,NO HOT WATER,RESIDENTIAL BUILDING,10021,...,NaN,The following complaint conditions are still o...,2026-07-14T00:00:00.000,MANHATTAN,08 MANHATTAN,05,1014290002,ONLINE,40.77124303640283,-73.95949953973174
4,69718280,2026-07-14T22:30:14.000,NaN,HPD,Department of Housing Preservation and Develop...,HEAT/HOT WATER,ENTIRE BUILDING,NO HOT WATER,RESIDENTIAL BUILDING,10003,...,NaN,The following complaint conditions are still o...,2026-07-14T00:00:00.000,MANHATTAN,03 MANHATTAN,02,1004690030,ONLINE,40.732128314538684,-73.9851198208051

In [44]:
print("Shape:", heat_df.shape)

Shape: (5, 23)

In [45]:
assert response.status_code == 200
assert len(records) == 5
assert heat_df["agency"].dropna().eq("HPD").all()
assert heat_df["complaint_type"].dropna().eq("HEAT/HOT WATER").all()
assert heat_df["unique_key"].notna().all()

print("Filtered API validation passed.")

Filtered API validation passed.

In [46]:
import sys
print(sys.executable)

D:\Projects\nyc311-heat-report\.venv\Scripts\python.exe

## PAGINATION TEST

In [47]:
PAGE_SIZE = 100

page_1_params = {
    **params,
    "$limit": PAGE_SIZE,
    "$offset": 0,
    "$order": "created_date DESC, unique_key DESC",
}

page_2_params = {
    **params,
    "$limit": PAGE_SIZE,
    "$offset": PAGE_SIZE,
    "$order": "created_date DESC, unique_key DESC",
}

In [48]:
page_1_response = requests.get(
    API_URL,
    params=page_1_params,
    timeout=30,
)

page_2_response = requests.get(
    API_URL,
    params=page_2_params,
    timeout=30,
)

page_1_response.raise_for_status()
page_2_response.raise_for_status()

page_1_records = page_1_response.json()
page_2_records = page_2_response.json()

print("Page 1 rows:", len(page_1_records))
print("Page 2 rows:", len(page_2_records))

Page 1 rows: 100
Page 2 rows: 100

In [49]:
page_1_keys = {
    record["unique_key"]
    for record in page_1_records
}

page_2_keys = {
    record["unique_key"]
    for record in page_2_records
}

assert len(page_1_records) == PAGE_SIZE
assert len(page_2_records) == PAGE_SIZE
assert page_1_keys.isdisjoint(page_2_keys)

print("Pagination validation passed.")
print("No duplicate unique keys across pages.")

Pagination validation passed.
No duplicate unique keys across pages.